// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutDocumentDataSlicesSlice = MediaTextSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

type HomeDocumentDataSlicesSlice = HeroWithCtaSlice;

/**
 * Content for Homepage documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type JadwalSantriDocumentDataSlicesSlice = TimetableListSlice;

/**
 * Content for Jadwal Santri documents
 */
interface JadwalSantriDocumentData {
  /**
   * Slice Zone field in *Jadwal Santri*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: jadwal_santri.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<JadwalSantriDocumentDataSlicesSlice> /**
   * Meta Title field in *Jadwal Santri*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: jadwal_santri.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Jadwal Santri*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: jadwal_santri.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Jadwal Santri*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: jadwal_santri.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Jadwal Santri document from Prismic
 *
 * - **API ID**: `jadwal_santri`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JadwalSantriDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JadwalSantriDocumentData>,
    "jadwal_santri",
    Lang
  >;

/**
 * Content for Contact Detail documents
 */
interface KontakDocumentData {
  /**
   * Nama Kontak field in *Contact Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Masukkan nama kontak
   * - **API ID Path**: kontak.nama_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  nama_kontak: prismic.KeyTextField;

  /**
   * Ikon Kontak field in *Contact Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cari icon di https://icon-sets.iconify.design/
   * - **API ID Path**: kontak.ikon_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ikon_kontak: prismic.KeyTextField;

  /**
   * Link Kontak field in *Contact Detail*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.link_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_kontak: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Contact Detail document from Prismic
 *
 * - **API ID**: `kontak`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontakDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<KontakDocumentData>, "kontak", Lang>;

type KontakkDocumentDataSlicesSlice = KontakSlice;

/**
 * Content for Kontakk documents
 */
interface KontakkDocumentData {
  /**
   * Slice Zone field in *Kontakk*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakk.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<KontakkDocumentDataSlicesSlice> /**
   * Meta Title field in *Kontakk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: kontakk.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Kontakk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: kontakk.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Kontakk*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: kontakk.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Kontakk document from Prismic
 *
 * - **API ID**: `kontakk`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontakkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<KontakkDocumentData>,
    "kontakk",
    Lang
  >;

type PendaftaranDocumentDataSlicesSlice = AdmissionsFlowSlice;

/**
 * Content for Pendaftaran documents
 */
interface PendaftaranDocumentData {
  /**
   * Slice Zone field in *Pendaftaran*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pendaftaran.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PendaftaranDocumentDataSlicesSlice> /**
   * Meta Title field in *Pendaftaran*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pendaftaran.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Pendaftaran*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pendaftaran.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Pendaftaran*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pendaftaran.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Pendaftaran document from Prismic
 *
 * - **API ID**: `pendaftaran`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PendaftaranDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PendaftaranDocumentData>,
    "pendaftaran",
    Lang
  >;

/**
 * Item in *Programs → Sub*
 */
export interface ProgramsDocumentDataSubProgramItem {
  /**
   * Judul Sub Program field in *Programs → Sub*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.sub_program[].sub_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Harga field in *Programs → Sub*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.sub_program[].pricing
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pricing: prismic.KeyTextField;

  /**
   * Action Button field in *Programs → Sub*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.sub_program[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Manfaat field in *Programs → Sub*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.sub_program[].benefits
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  benefits: prismic.RichTextField;
}

type ProgramsDocumentDataSlicesSlice = never;

/**
 * Content for Programs documents
 */
interface ProgramsDocumentData {
  /**
   * Judul Program field in *Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Sub field in *Programs*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.sub_program[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  sub_program: prismic.GroupField<Simplify<ProgramsDocumentDataSubProgramItem>>;

  /**
   * Slice Zone field in *Programs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProgramsDocumentDataSlicesSlice> /**
   * Meta Title field in *Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: programs.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: programs.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Programs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: programs.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Programs document from Prismic
 *
 * - **API ID**: `programs`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProgramsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProgramsDocumentData>,
    "programs",
    Lang
  >;

/**
 * Item in *Nav&Footer → Social Media*
 */
export interface RootDocumentDataSocmedListItem {
  /**
   * Ikon Kontak field in *Nav&Footer → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cari icon di https://icon-sets.iconify.design/
   * - **API ID Path**: root.socmed_list[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Link Kontak field in *Nav&Footer → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: root.socmed_list[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type RootDocumentDataSlicesSlice = never;

/**
 * Content for Nav&Footer documents
 */
interface RootDocumentData {
  /**
   * Logo field in *Nav&Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: root.icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *Nav&Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Copyright field in *Nav&Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: root.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField;

  /**
   * Social Media field in *Nav&Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: root.socmed_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socmed_list: prismic.GroupField<Simplify<RootDocumentDataSocmedListItem>>;

  /**
   * Slice Zone field in *Nav&Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: root.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RootDocumentDataSlicesSlice> /**
   * Meta Title field in *Nav&Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: root.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Nav&Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: root.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Nav&Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: root.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Nav&Footer document from Prismic
 *
 * - **API ID**: `root`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RootDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<RootDocumentData>, "root", Lang>;

type VisiMisiDocumentDataSlicesSlice = ContentImageSideSlice;

/**
 * Content for Visi Misi documents
 */
interface VisiMisiDocumentData {
  /**
   * Slice Zone field in *Visi Misi*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: visi_misi.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<VisiMisiDocumentDataSlicesSlice> /**
   * Meta Title field in *Visi Misi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: visi_misi.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Visi Misi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: visi_misi.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Visi Misi*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: visi_misi.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Visi Misi document from Prismic
 *
 * - **API ID**: `visi_misi`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisiMisiDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VisiMisiDocumentData>,
    "visi_misi",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | HomeDocument
  | JadwalSantriDocument
  | KontakDocument
  | KontakkDocument
  | PendaftaranDocument
  | ProgramsDocument
  | RootDocument
  | VisiMisiDocument;

/**
 * Item in *Pendaftaran → Default → Primary → Procedural Steps*
 */
export interface AdmissionsFlowSliceDefaultPrimaryStepsItem {
  /**
   * Step Title field in *Pendaftaran → Default → Primary → Procedural Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.steps[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_title: prismic.RichTextField;

  /**
   * Step Description field in *Pendaftaran → Default → Primary → Procedural Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.steps[].step_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_description: prismic.RichTextField;
}

/**
 * Item in *Pendaftaran → Default → Primary → Requirements List*
 */
export interface AdmissionsFlowSliceDefaultPrimaryRequirementsItem {
  /**
   * Requirement Title field in *Pendaftaran → Default → Primary → Requirements List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.requirements[].requirement_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  requirement_title: prismic.KeyTextField;

  /**
   * Requirement Details field in *Pendaftaran → Default → Primary → Requirements List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.requirements[].requirement_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  requirement_details: prismic.RichTextField;
}

/**
 * Primary content in *Pendaftaran → Default → Primary*
 */
export interface AdmissionsFlowSliceDefaultPrimary {
  /**
   * Main Title field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.main_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_title: prismic.RichTextField;

  /**
   * Main Description field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.main_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_description: prismic.RichTextField;

  /**
   * Call to Action Button field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Visual Image field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.visual_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  visual_image: prismic.ImageField<never>;

  /**
   * Procedural Steps field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<AdmissionsFlowSliceDefaultPrimaryStepsItem>
  >;

  /**
   * Requirements Heading field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.requirements_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  requirements_heading: prismic.RichTextField;

  /**
   * Requirements List field in *Pendaftaran → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: admissions_flow.default.primary.requirements[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  requirements: prismic.GroupField<
    Simplify<AdmissionsFlowSliceDefaultPrimaryRequirementsItem>
  >;
}

/**
 * Default variation for Pendaftaran Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout combining introductory info, procedural steps, and expandable requirement sections.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdmissionsFlowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AdmissionsFlowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pendaftaran*
 */
type AdmissionsFlowSliceVariation = AdmissionsFlowSliceDefault;

/**
 * Pendaftaran Shared Slice
 *
 * - **API ID**: `admissions_flow`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AdmissionsFlowSlice = prismic.SharedSlice<
  "admissions_flow",
  AdmissionsFlowSliceVariation
>;

/**
 * Primary content in *VisiMisi → Default → Primary*
 */
export interface ContentImageSideSliceDefaultPrimary {
  /**
   * Visi field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.visi
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  visi: prismic.KeyTextField;

  /**
   * Misi field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Side Image field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.side_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  side_image: prismic.ImageField<never>;
}

/**
 * Default variation for VisiMisi Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with main content and one image aligned side by side.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentImageSideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentImageSideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisiMisi*
 */
type ContentImageSideSliceVariation = ContentImageSideSliceDefault;

/**
 * VisiMisi Shared Slice
 *
 * - **API ID**: `content_image_side`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentImageSideSlice = prismic.SharedSlice<
  "content_image_side",
  ContentImageSideSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Social Media*
 */
export interface FooterSliceDefaultPrimarySocmedListItem {
  /**
   * Ikon Kontak field in *Footer → Default → Primary → Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cari icon di https://icon-sets.iconify.design/
   * - **API ID Path**: footer.default.primary.socmed_list[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Link Kontak field in *Footer → Default → Primary → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.socmed_list[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Icon field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Description field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Copyright field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.copyright
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField;

  /**
   * Social Media field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.socmed_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socmed_list: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimarySocmedListItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Jumbotron → Default → Primary*
 */
export interface HeroWithCtaSliceDefaultPrimary {
  /**
   * Title field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Button field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background Image field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Jumbotron Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with heading, description, CTA button, and background image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Jumbotron*
 */
type HeroWithCtaSliceVariation = HeroWithCtaSliceDefault;

/**
 * Jumbotron Shared Slice
 *
 * - **API ID**: `hero_with_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithCtaSlice = prismic.SharedSlice<
  "hero_with_cta",
  HeroWithCtaSliceVariation
>;

/**
 * Item in *Kontak → Default → Primary → List Kontak*
 */
export interface KontakSliceDefaultPrimaryContactListItem {
  /**
   * Ikon Kontak field in *Kontak → Default → Primary → List Kontak*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cari icon di https://icon-sets.iconify.design/
   * - **API ID Path**: kontak.default.primary.contact_list[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Nama Media/Platform field in *Kontak → Default → Primary → List Kontak*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.contact_list[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * Link Menuju Kontak field in *Kontak → Default → Primary → List Kontak*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Masukan Label Kontak di sini
   * - **API ID Path**: kontak.default.primary.contact_list[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Kontak → Default → Primary*
 */
export interface KontakSliceDefaultPrimary {
  /**
   * Alamat field in *Kontak → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.alamat
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  alamat: prismic.KeyTextField;

  /**
   * Google Map field in *Kontak → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.gmaps
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  gmaps: prismic.GeoPointField;

  /**
   * List Kontak field in *Kontak → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.contact_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_list: prismic.GroupField<
    Simplify<KontakSliceDefaultPrimaryContactListItem>
  >;
}

/**
 * Default variation for Kontak Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KontakSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KontakSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Kontak*
 */
type KontakSliceVariation = KontakSliceDefault;

/**
 * Kontak Shared Slice
 *
 * - **API ID**: `kontak`
 * - **Description**: Kontak
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type KontakSlice = prismic.SharedSlice<"kontak", KontakSliceVariation>;

/**
 * Item in *About → Image Left / Text Right → Primary → List Sosial Media*
 */
export interface MediaTextSliceImageLeftTextRightPrimarySocmedListItem {}

/**
 * Primary content in *About → Image Left / Text Right → Primary*
 */
export interface MediaTextSliceImageLeftTextRightPrimary {
  /**
   * Judul field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.judul
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  judul: prismic.KeyTextField;

  /**
   * Media field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;

  /**
   * Description field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * List Sosial Media field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.socmed_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  socmed_list: prismic.GroupField<
    Simplify<MediaTextSliceImageLeftTextRightPrimarySocmedListItem>
  >;
}

/**
 * Image Left / Text Right variation for About Slice
 *
 * - **API ID**: `image_left_text_right`
 * - **Description**: Displays the image or media on the left and heading with text content on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaTextSliceImageLeftTextRight = prismic.SharedSliceVariation<
  "image_left_text_right",
  Simplify<MediaTextSliceImageLeftTextRightPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type MediaTextSliceVariation = MediaTextSliceImageLeftTextRight;

/**
 * About Shared Slice
 *
 * - **API ID**: `media_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaTextSlice = prismic.SharedSlice<
  "media_text",
  MediaTextSliceVariation
>;

/**
 * Default variation for Programs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Programs*
 */
type ProgramsSliceVariation = ProgramsSliceDefault;

/**
 * Programs Shared Slice
 *
 * - **API ID**: `programs`
 * - **Description**: Programs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramsSlice = prismic.SharedSlice<
  "programs",
  ProgramsSliceVariation
>;

/**
 * Item in *JadwalSantri → Default → Primary → Periods*
 */
export interface TimetableListSliceDefaultPrimaryPeriodsItem {
  /**
   * Period Name field in *JadwalSantri → Default → Primary → Periods*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timetable_list.default.primary.periods[].period_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  period_name: prismic.KeyTextField;

  /**
   * Jadwal field in *JadwalSantri → Default → Primary → Periods*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: timetable_list.default.primary.periods[].schedule
   * - **Documentation**: https://prismic.io/docs/fields/table
   */
  schedule: prismic.TableField;
}

/**
 * Primary content in *JadwalSantri → Default → Primary*
 */
export interface TimetableListSliceDefaultPrimary {
  /**
   * Title field in *JadwalSantri → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timetable_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Gambar field in *JadwalSantri → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: timetable_list.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Periods field in *JadwalSantri → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timetable_list.default.primary.periods[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  periods: prismic.GroupField<
    Simplify<TimetableListSliceDefaultPrimaryPeriodsItem>
  >;
}

/**
 * Default variation for JadwalSantri Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a heading and a list of time periods, each with multiple activities.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimetableListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TimetableListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JadwalSantri*
 */
type TimetableListSliceVariation = TimetableListSliceDefault;

/**
 * JadwalSantri Shared Slice
 *
 * - **API ID**: `timetable_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimetableListSlice = prismic.SharedSlice<
  "timetable_list",
  TimetableListSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      JadwalSantriDocument,
      JadwalSantriDocumentData,
      JadwalSantriDocumentDataSlicesSlice,
      KontakDocument,
      KontakDocumentData,
      KontakkDocument,
      KontakkDocumentData,
      KontakkDocumentDataSlicesSlice,
      PendaftaranDocument,
      PendaftaranDocumentData,
      PendaftaranDocumentDataSlicesSlice,
      ProgramsDocument,
      ProgramsDocumentData,
      ProgramsDocumentDataSubProgramItem,
      ProgramsDocumentDataSlicesSlice,
      RootDocument,
      RootDocumentData,
      RootDocumentDataSocmedListItem,
      RootDocumentDataSlicesSlice,
      VisiMisiDocument,
      VisiMisiDocumentData,
      VisiMisiDocumentDataSlicesSlice,
      AllDocumentTypes,
      AdmissionsFlowSlice,
      AdmissionsFlowSliceDefaultPrimaryStepsItem,
      AdmissionsFlowSliceDefaultPrimaryRequirementsItem,
      AdmissionsFlowSliceDefaultPrimary,
      AdmissionsFlowSliceVariation,
      AdmissionsFlowSliceDefault,
      ContentImageSideSlice,
      ContentImageSideSliceDefaultPrimary,
      ContentImageSideSliceVariation,
      ContentImageSideSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimarySocmedListItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroWithCtaSlice,
      HeroWithCtaSliceDefaultPrimary,
      HeroWithCtaSliceVariation,
      HeroWithCtaSliceDefault,
      KontakSlice,
      KontakSliceDefaultPrimaryContactListItem,
      KontakSliceDefaultPrimary,
      KontakSliceVariation,
      KontakSliceDefault,
      MediaTextSlice,
      MediaTextSliceImageLeftTextRightPrimarySocmedListItem,
      MediaTextSliceImageLeftTextRightPrimary,
      MediaTextSliceVariation,
      MediaTextSliceImageLeftTextRight,
      ProgramsSlice,
      ProgramsSliceVariation,
      ProgramsSliceDefault,
      TimetableListSlice,
      TimetableListSliceDefaultPrimaryPeriodsItem,
      TimetableListSliceDefaultPrimary,
      TimetableListSliceVariation,
      TimetableListSliceDefault,
    };
  }
}
