// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | MediaTextSlice
  | ContentImageSideSlice
  | HeroWithCtaSlice;

/**
 * Content for Homepage documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Kontak documents
 */
interface KontakDocumentData {
  /**
   * Nama Kontak field in *Kontak*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Masukkan nama kontak
   * - **API ID Path**: kontak.nama_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nama_kontak: prismic.KeyTextField;

  /**
   * Ikon Kontak field in *Kontak*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cari icon di https://icon-sets.iconify.design/
   * - **API ID Path**: kontak.ikon_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ikon_kontak: prismic.KeyTextField;

  /**
   * Link Kontak field in *Kontak*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.link_kontak
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_kontak: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Kontak document from Prismic
 *
 * - **API ID**: `kontak`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type KontakDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<KontakDocumentData>, "kontak", Lang>;

export type AllDocumentTypes = HomeDocument | KontakDocument;

/**
 * Primary content in *VisiMisi → Default → Primary*
 */
export interface ContentImageSideSliceDefaultPrimary {
  /**
   * Visi field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.visi
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  visi: prismic.KeyTextField;

  /**
   * Misi field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Side Image field in *VisiMisi → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_image_side.default.primary.side_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  side_image: prismic.ImageField<never>;
}

/**
 * Default variation for VisiMisi Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with main content and one image aligned side by side.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentImageSideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentImageSideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisiMisi*
 */
type ContentImageSideSliceVariation = ContentImageSideSliceDefault;

/**
 * VisiMisi Shared Slice
 *
 * - **API ID**: `content_image_side`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentImageSideSlice = prismic.SharedSlice<
  "content_image_side",
  ContentImageSideSliceVariation
>;

/**
 * Primary content in *Jumbotron → Default → Primary*
 */
export interface HeroWithCtaSliceDefaultPrimary {
  /**
   * Title field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Button field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Background Image field in *Jumbotron → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_cta.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Jumbotron Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero with heading, description, CTA button, and background image.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Jumbotron*
 */
type HeroWithCtaSliceVariation = HeroWithCtaSliceDefault;

/**
 * Jumbotron Shared Slice
 *
 * - **API ID**: `hero_with_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithCtaSlice = prismic.SharedSlice<
  "hero_with_cta",
  HeroWithCtaSliceVariation
>;

/**
 * Item in *Kontak → Default → Primary → Daftar Kontak*
 */
export interface KontakSliceDefaultPrimaryDaftarKontakItem {
  /**
   * Detail Kontak field in *Kontak → Default → Primary → Daftar Kontak*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.daftar_kontak[].contact_detail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  contact_detail: prismic.ContentRelationshipField<"kontak">;
}

/**
 * Primary content in *Kontak → Default → Primary*
 */
export interface KontakSliceDefaultPrimary {
  /**
   * Daftar Kontak field in *Kontak → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.daftar_kontak[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  daftar_kontak: prismic.GroupField<
    Simplify<KontakSliceDefaultPrimaryDaftarKontakItem>
  >;

  /**
   * Link Google MAP field in *Kontak → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: kontak.default.primary.gmaps_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gmaps_link: prismic.KeyTextField;
}

/**
 * Default variation for Kontak Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KontakSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KontakSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Kontak*
 */
type KontakSliceVariation = KontakSliceDefault;

/**
 * Kontak Shared Slice
 *
 * - **API ID**: `kontak`
 * - **Description**: Kontak
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KontakSlice = prismic.SharedSlice<"kontak", KontakSliceVariation>;

/**
 * Primary content in *About → Image Left / Text Right → Primary*
 */
export interface MediaTextSliceImageLeftTextRightPrimary {
  /**
   * Judul field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.judul
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  judul: prismic.KeyTextField;

  /**
   * Media field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;

  /**
   * Description field in *About → Image Left / Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_text.image_left_text_right.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Image Left / Text Right variation for About Slice
 *
 * - **API ID**: `image_left_text_right`
 * - **Description**: Displays the image or media on the left and heading with text content on the right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaTextSliceImageLeftTextRight = prismic.SharedSliceVariation<
  "image_left_text_right",
  Simplify<MediaTextSliceImageLeftTextRightPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type MediaTextSliceVariation = MediaTextSliceImageLeftTextRight;

/**
 * About Shared Slice
 *
 * - **API ID**: `media_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaTextSlice = prismic.SharedSlice<
  "media_text",
  MediaTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      KontakDocument,
      KontakDocumentData,
      AllDocumentTypes,
      ContentImageSideSlice,
      ContentImageSideSliceDefaultPrimary,
      ContentImageSideSliceVariation,
      ContentImageSideSliceDefault,
      HeroWithCtaSlice,
      HeroWithCtaSliceDefaultPrimary,
      HeroWithCtaSliceVariation,
      HeroWithCtaSliceDefault,
      KontakSlice,
      KontakSliceDefaultPrimaryDaftarKontakItem,
      KontakSliceDefaultPrimary,
      KontakSliceVariation,
      KontakSliceDefault,
      MediaTextSlice,
      MediaTextSliceImageLeftTextRightPrimary,
      MediaTextSliceVariation,
      MediaTextSliceImageLeftTextRight,
    };
  }
}
