// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  content_image_side: defineAsyncComponent(
    () => import("./VisiMisi/index.vue"),
  ),
  hero_with_cta: defineAsyncComponent(() => import("./Jumbotron/index.vue")),
  kontak: defineAsyncComponent(() => import("./Kontak/index.vue")),
  media_text: defineAsyncComponent(() => import("./About/index.vue")),
});
